# Generated by Django 4.2.5 on 2023-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('age', models.IntegerField()),
                ('biography', models.TextField()),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('max_votes', models.IntegerField(default=0)),
                ('persons', models.ManyToManyField(to='votingApi.person')),
            ],
        ),
    ]
