# Generated by Django 4.2.5 on 2023-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
