# Generated by Django 4.2.5 on 2023-09-10 22:54

from django.db import migrations, models
import django.db.models.deletion
import votingApi.models


class Migration(migrations.Migration):

    dependencies = [
        ('votingApi', '0002_voting_active_alter_person_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='votes',
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to=votingApi.models.path_and_rename),
        ),
        migrations.CreateModel(
            name='PersonVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApi.person')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingApi.voting')),
            ],
        ),
    ]
